server:
  port: 7000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  application:
    name: a-service
logging:
  level:
    root: info #为演示需要，开启debug级别日志
feign:
  httpclient:
    enabled: true
